version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lostfound-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lostfound_db
      MYSQL_USER: lostfound_user
      MYSQL_PASSWORD: lostfound_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lostfound-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=lostfound_user
      - DB_PASSWORD=lostfound_password
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/lostfound_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

volumes:
  mysql_data: 