version: '3.8'

services:
  lostfound-mysql:
    image: mysql:8.0
    container_name: lostfound-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lostfound_db
      MYSQL_USER: lostfound_user
      MYSQL_PASSWORD: lostfound_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lostfound-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      interval: 10s
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lostfound-app
    depends_on:
      lostfound-mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=lostfound_user
      - DB_PASSWORD=lostfound_password
      - SPRING_DATASOURCE_URL=jdbc:mysql://lostfound-mysql:3306/lostfound_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - "9095:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - lostfound-network

networks:
  lostfound-network:
    driver: bridge

volumes:
  mysql_data: 