spring:
  application:
    name: lost-found-service
  
  # Database Configuration
  datasource:
    # url: jdbc:mysql://localhost:3306/lostfound_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    # username: ${DB_USERNAME:lostfound_user}
    # password: ${DB_PASSWORD:lostfound_password}
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always


# File Processing Configuration
file:
  upload:
    directory: ${UPLOAD_DIR:./uploads}
    supported-types:
      - application/pdf
    max-size: 10485760 # 10MB in bytes

# Logging Configuration
logging:
  level:
    com.example.lostfound: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/lostfound.log

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

# Custom Application Properties
app:
  name: Lost and Found Service
  version: 1.0.0
  description: A comprehensive lost and found management system
  admin:
    default-username: ${ADMIN_USERNAME:admin}
    default-password: ${ADMIN_PASSWORD:admin123}
  pagination:
    default-page-size: 20
    max-page-size: 100 